export const PROPERTY_TYPES = [
  { value: "apartment", label: "Appartement" },
  { value: "apartment_furnished", label: "Appartement meublé" },
  { value: "apartment_unfurnished", label: "Appartement non meublé" },
  { value: "studio", label: "Studio" },
  { value: "studio_simple", label: "Studio simple" },
  { value: "studio_modern", label: "Studio moderne" },
  { value: "room", label: "Chambre simple" },
  { value: "room_modern", label: "Chambre moderne" },
  { value: "room_furnished", label: "Chambre meublée" },
  { value: "villa", label: "Villa" },
  { value: "duplex", label: "Duplex" },
  { value: "house", label: "Maison" },
  { value: "land", label: "Terrain" },
  { value: "commercial", label: "Local commercial" },
  { value: "shop", label: "Magasin / Boutique" },
  { value: "warehouse", label: "Entrepôt" },
  { value: "coworking", label: "Espace de co-working" },
  { value: "hotel_room", label: "Chambre d'hôtel" },
  { value: "office", label: "Bureau" },
  { value: "building", label: "Immeuble" },
  { value: "parking", label: "Parking" },
  { value: "other", label: "Autre" },
];

export const AMENITIES = [
  { key: "hasGarden", label: "Jardin" },
  { key: "hasPool", label: "Piscine" },
  { key: "hasGarage", label: "Garage" },
  { key: "hasTerrace", label: "Terrasse" },
  { key: "hasBalcony", label: "Balcon" }, // ⬅️ ajouté — corrige
  { key: "hasVeranda", label: "Véranda" },
  { key: "hasElevator", label: "Ascenseur" },
  { key: "hasParking", label: "Parking" },
  { key: "hasCellar", label: "Cave" },
  { key: "hasAirConditioning", label: "Climatisation" },
  { key: "hasAlarm", label: "Alarme" },
  { key: "hasIntercom", label: "Interphone" },
  { key: "isFurnished", label: "Meublé" },
  { key: "hasLivingRoom", label: "Salon" },
  { key: "hasKitchen", label: "Cuisine équipée" },
  { key: "hasShower", label: "Douche" },
  { key: "hasBathroom", label: "Salle de bain" },
];

export const EXTRA_FEATURES = [
  { key: "hasWaterTank", label: "Réservoir d'eau" },
  { key: "hasGenerator", label: "Groupe électrogène" },
  { key: "hasSolarPanels", label: "Panneaux solaires" },
  { key: "hasSecurity", label: "Sécurité 24/7" },
  { key: "hasFence", label: "Clôture" },
  { key: "hasBorehole", label: "Forage" },
];
